import nodes


class VarMaker(object):
    """Make new variables with names guaranteed not to conflict with
    any explicit query variable or any other variable generated by
    this class."""

    _varNr = 0

    @classmethod
    def make(cls):
        cls._varNr += 1
        return nodes.Var('#var_%d#' % cls._varNr)


