import antlr

from relrdf.expression import literal, nodes


class Parser(antlr.LLkParser):
    """The base class for the SPARQL parser generated by ANTLR."""

    __slots__ = ()

    def __init__(self, *args, **kwargs):
        super(Parser, self).__init__(*args, **kwargs)


    @staticmethod
    def makeTypedLiteral(string, typeUri):
        lt = literal.Literal(string, typeUri=typeUri)
        return nodes.Literal(lt)

